version: 2
jobs:
  build1:
    docker:
      - image: circleci/php:7.0-apache-node-browsers
    steps:
      - run: echo "Hello 1"

  build2:
    docker:
      - image: circleci/php:7.0-apache-node-browsers
    steps:
      - run: echo "Hello 2"
      - run: exit 1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build1
      - build2
